Creeper max_fuse_ticks Tag and Mech
DenizenScript/Denizen-For-Bukkit pull request #1904
Opened 2019-02-03 22:59 UTC by Xenmai

2019-02-03 23:01 UTC, mcmonkey4eva commented on plugin/src/main/java/net/aufdemrand/denizen/objects/properties/entity/EntityMaxFuseTicks.java
> +        return entity.getBukkitEntity() instanceof Creeper ? ((Creeper) entity.getBukkitEntity()).getMaxFuseTicks() + "" : null;
Unneeded tern (it's always a creeper if it's reading this line)

2019-02-03 23:02 UTC, mcmonkey4eva commented on plugin/src/main/java/net/aufdemrand/denizen/objects/properties/entity/EntityMaxFuseTicks.java
> +        if (mechanism.matches("max_fuse_ticks") && entity.getBukkitEntity() instanceof Creeper && mechanism.requireInteger()) {
unneeded instanceof check for same reason as above

2019-02-03 23:02 UTC, mcmonkey4eva commented on plugin/src/main/java/net/aufdemrand/denizen/objects/properties/entity/EntityMaxFuseTicks.java
> +        // @returns Element(Integer)
bad meta

2019-02-03 23:02 UTC, mcmonkey4eva commented on plugin/src/main/java/net/aufdemrand/denizen/objects/properties/entity/EntityMaxFuseTicks.java
> +        // @input Element(Integer)
bad meta

2019-02-03 23:03 UTC, mcmonkey4eva commented on plugin/src/main/java/net/aufdemrand/denizen/objects/properties/entity/EntityMaxFuseTicks.java
> +        if (attribute.startsWith("max_fuse_ticks") && entity.getBukkitEntity() instanceof Creeper) {
unneeded check

2019-02-03 23:03 UTC, mcmonkey4eva commented on plugin/src/main/java/net/aufdemrand/denizen/objects/properties/entity/EntityMaxFuseTicks.java
> +        // Returns the number of fuse ticks a creeper will default to when not triggered.
Confusing sentence

2019-02-03 23:03 UTC, mcmonkey4eva commented on plugin/src/main/java/net/aufdemrand/denizen/objects/properties/entity/EntityMaxFuseTicks.java
> +        // Sets the number of fuse ticks a creeper will default to when not triggered
Confusing sentence, missing period

2019-02-03 23:44 UTC, mcmonkey4eva commented on plugin/src/main/java/net/aufdemrand/denizen/objects/properties/entity/EntityMaxFuseTicks.java
> +        // Sets the default number of ticks until the creeper explodes when primed (NOT the time remaining if already primed)
Period at end of sentence

2019-02-03 23:46 UTC, mergu requested changes

2019-02-03 23:46 UTC, mergu commented on plugin/src/main/java/net/aufdemrand/denizen/objects/properties/entity/EntityMaxFuseTicks.java
> +    public static final String[] handledTags = new String[]{
Missing space before brace

2019-02-03 23:46 UTC, mergu commented on plugin/src/main/java/net/aufdemrand/denizen/objects/properties/entity/EntityMaxFuseTicks.java
> +        return ((Creeper) entity.getBukkitEntity()).getMaxFuseTicks() + "";
Use String.valueOf() here instead of appending an empty string

2019-02-04 08:00 UTC, mcmonkey4eva commented
I just fixed it myself and manually merged, thanks!

2019-02-04 08:00 UTC, closed without merging