Pink petal count
DenizenScript/Denizen-For-Bukkit pull request #2632
Opened 2024-06-25 02:16 UTC by zozer

Added count property to pink petals

2024-06-25 02:49 UTC, mcmonkey4eva commented on plugin/src/main/java/com/denizenscript/denizen/utilities/MultiVersionHelper1_19.java
> +    public static int getCount(MaterialTag material) {
should have newlines between the methods

2024-06-25 03:16 UTC, mcmonkey4eva submitted a review, later dismissed

2024-08-31 13:32 UTC, tal5 commented
See [message](https://discord.com/channels/315163488085475337/1011496047811506227/1258173771689496718) on Discord - not really able to test rn, but afaics it should work fine? having version helper methods isn't awful, but would be nicer to just do it normally if possible

2025-01-23 23:17 UTC, mcmonkey4eva approved these changes, later dismissed

2025-01-29 11:02 UTC, tal5 requested changes

2025-01-29 11:02 UTC, tal5 commented on plugin/src/main/java/com/denizenscript/denizen/objects/properties/material/MaterialCount.java
> +        else if ((NMSHandler.getVersion().isAtLeast(NMSVersion.v1_19) && material.getModernData() instanceof PinkPetals pinkPetals)) {
Pretty sure these are redundant double brackets on all of these?

2025-02-03 17:34 UTC, mcmonkey4eva approved these changes

2025-03-01 18:31 UTC, tal5 approved these changes

2025-03-01 18:32 UTC, merged