Modernized Properties Part 6
DenizenScript/Denizen-For-Bukkit pull request #2660
Opened 2024-10-31 22:16 UTC by heypr

- Modernized `MaterialTag.unstable` property.
- Modernized `MaterialTag.waterlogged` property.
- Modernized `MaterialTag.count` property.

2024-12-23 10:07 UTC, mcmonkey4eva approved these changes, later dismissed

2024-12-25 14:50 UTC, tal5 requested changes

2024-12-25 14:50 UTC, tal5 commented on plugin/src/main/java/com/denizenscript/denizen/objects/properties/material/MaterialDistance.java
> +        }
There's shouldn't be any need to keep `getFrom` - if anything is using this property directly, can use `describes` & add a constructor that directs to `super`.
In general should ideally remove the older methods when updating a property, any `is/getX` methods can just be `instanceof` pattern matching, any `get/setDistance` sorta methods can usually just be put directly in `get/setPropertyValue`, etc..
It's not an absolute _requirement_, but it'd be nicer to have the properties fully match the modern format.

2024-12-25 14:50 UTC, tal5 commented on plugin/src/main/java/com/denizenscript/denizen/objects/properties/material/MaterialDistance.java
> +    MaterialTag material;
Should remove the old field and use the built-in `object` field.

2024-12-25 14:50 UTC, tal5 commented on plugin/src/main/java/com/denizenscript/denizen/objects/properties/material/MaterialHalf.java
> +    // For the half name, see <@link tag MaterialTag.half>.
Isn't that just linking to itself? should already automatically be in the mechanism's tag link

2024-12-25 14:50 UTC, tal5 commented on plugin/src/main/java/com/denizenscript/denizen/objects/properties/material/MaterialDistance.java
> +    MaterialTag material;
And with that, should use the `MaterialProperty` methods (e.g. `getBlockData()` instead of `material.getModernData()`)

2025-03-01 19:11 UTC, tal5 requested changes

2025-03-01 19:11 UTC, tal5 commented on plugin/src/main/java/com/denizenscript/denizen/objects/properties/material/MaterialFaces.java
> +    // Controls a list of the current faces for a material that has multiple faces (like a mushroom block).
Should include what can the faces actually be (either an example like the old meta, and/or a link to `MaterialTag.valid_faces`).
Also, probably something like `Controls the current faces of a material...`?

2025-03-01 19:11 UTC, tal5 commented on plugin/src/main/java/com/denizenscript/denizen/objects/properties/material/MaterialFaces.java
>      public ListTag getFaceList() {
Is there any reason to keep this & `getFaces`? seems like they can be removed/moved into the new property methods like the other properties.

2025-03-01 19:11 UTC, tal5 commented on plugin/src/main/java/com/denizenscript/denizen/objects/properties/material/MaterialFaces.java
> +        return data instanceof MultipleFacing;
Don't think there's a need for a variable here, can just call it directly in the `instanceof`

2025-03-01 19:11 UTC, tal5 commented on plugin/src/main/java/com/denizenscript/denizen/objects/properties/material/MaterialHalf.java
> +    // Controls the current half for a bisected material (like a door, double-plant, chest, or a bed).
Maybe `Controls a bisected material's current half (like a door, double-plant, chest, or a bed)`? `for a` sounds weird

2025-03-01 19:11 UTC, tal5 commented on plugin/src/main/java/com/denizenscript/denizen/objects/properties/material/MaterialHalf.java
> +        return new ElementTag(getHalfName());
if `getHalfName` is nullable you'd need to handle that there - but also, is there any reason to keep these methods as opposed to just handling that within `getPropertyValue`?

2025-05-05 20:56 UTC, mcmonkey4eva commented on plugin/src/main/java/com/denizenscript/denizen/objects/properties/material/MaterialFaces.java
> +            faces.add(face.name());
just `add(face)` I think, or `add(face.name(), true)`

2025-05-05 20:57 UTC, mcmonkey4eva commented on plugin/src/main/java/com/denizenscript/denizen/objects/properties/material/MaterialFaces.java
> +            faces.add(face.name());
or use the listtag stream constructor if that works here

2025-05-20 21:26 UTC, tal5 requested changes

2025-05-20 21:26 UTC, tal5 commented on plugin/src/main/java/com/denizenscript/denizen/objects/properties/material/MaterialHalf.java
> +            return new ElementTag(bisected.getHalf().name());
All of these `.name()`s are redundant, pass the enum in directly

2025-05-20 21:26 UTC, tal5 commented on plugin/src/main/java/com/denizenscript/denizen/objects/properties/material/MaterialHalf.java
> +            bisected.setHalf(value.asEnum(Bisected.Half.class));
Should add `Mechanism#requireEnum` calls

2025-05-20 21:26 UTC, tal5 commented on plugin/src/main/java/com/denizenscript/denizen/objects/properties/material/MaterialFaces.java
> +            facing.setFace(BlockFace.valueOf(faceName.toUpperCase()), true);
Should ideally have some proper error checking (currently it'll just throw an exception for invalid input).
I'd `ElementTag#asEnum` (the static one), and then null check -> error & `continue`.

2025-06-18 12:35 UTC, mcmonkey4eva commented on plugin/src/main/java/com/denizenscript/denizen/objects/properties/material/MaterialFaces.java
> +    // @name valid_faces
this is wrong meta

2025-08-24 03:22 UTC, mcmonkey4eva commented
Closing to de-clutter PR list, when this can be finished let us know and we'll reopen.

2025-08-24 03:22 UTC, closed without merging