Minor Fixes
DenizenScript/Denizen-For-Bukkit pull request #2673
Opened 2024-11-11 23:47 UTC by MC-Samuel

Added a couple missing @Override's and converted a couple tags and mechs to properties

2024-11-17 01:35 UTC, mcmonkey4eva commented on plugin/src/main/java/com/denizenscript/denizen/objects/properties/entity/EntityCannotEnterHive.java
> +        return new DurationTag(as(Bee.class).getCannotEnterHiveTicks());
I don't think removing the `(long)` conversion is valid here. Have you tested that this property still works as intended, including returning values that make sense?

2024-11-18 21:58 UTC, mcmonkey4eva approved these changes, later dismissed

2024-11-21 06:43 UTC, MC-Samuel commented
Added "EntityAwake" property, requested in https://discord.com/channels/315163488085475337/1301429345172193332

2024-11-21 07:07 UTC, mcmonkey4eva commented
That's entirely unrelated to what this PR previously contained, please separate it

2024-11-21 08:57 UTC, mcmonkey4eva submitted a review, later dismissed

2024-12-07 10:01 UTC, tal5 requested changes

2024-12-07 10:01 UTC, tal5 commented on plugin/src/main/java/com/denizenscript/denizen/objects/properties/entity/EntityCanJoinRaid.java
> +    // If the entity is raider mob (like a pillager), controls whether the entity is allowed to join active raids.
Should prefer the `Controls X` meta format so the meta site can adapt it into the tag/mech meta

2024-12-07 10:01 UTC, tal5 commented on plugin/src/main/java/com/denizenscript/denizen/objects/properties/entity/EntityCannotEnterHive.java
> +        if (mechanism.requireObject(DurationTag.class)) {
Don't believe this `requireObject` is needed? it already verifies it got a `DurationTag` since you passed that in `autoRegister`

2024-12-07 10:01 UTC, tal5 commented on plugin/src/main/java/com/denizenscript/denizen/objects/properties/entity/EntityCannotEnterHive.java
> +            as(Bee.class).setCannotEnterHiveTicks(mechanism.valueAsType(DurationTag.class).getTicksAsInt());
Should just use the `DurationTag param` passed into the method.

2024-12-08 06:26 UTC, mcmonkey4eva approved these changes

2024-12-09 19:55 UTC, tal5 approved these changes

2024-12-09 19:57 UTC, merged