shearable entities support
DenizenScript/Denizen-For-Bukkit pull request #2679
Opened 2024-12-03 13:22 UTC by Hydroxycobalamin

This PR:

- moves EntityTag.is_sheared tag and EntityTag.sheared mechanism into a EntityProperty, supporting Sheep, Bogged and Snow golems.
- deprecates EntityTag.is_sheared tag in favor of the property.
- adds paper-only EntityTag.shear mechanism to allow mushroom cows and other shearable entities to be sheared naturally, including drops.

Support for bogged entities were requested on Discord. https://discord.com/channels/315163488085475337/1291520367495614574/1291520367495614574

2024-12-03 13:50 UTC, mcmonkey4eva commented on paper/src/main/java/com/denizenscript/denizen/paper/properties/PaperEntityExtensions.java
> +            // # - adjust <player.target> shear:
the trailing colon shouldn't be required here

2024-12-03 13:50 UTC, mcmonkey4eva commented on plugin/src/main/java/com/denizenscript/denizen/objects/properties/entity/EntitySheared.java
> +    // Controls whether a sheep is sheared, a bogged is harvested or a snow golem is derped, eg not wearing a pumpkin.
`ie` not `eg`.

2024-12-03 13:51 UTC, mcmonkey4eva commented on plugin/src/main/java/com/denizenscript/denizen/objects/properties/entity/EntitySheared.java
> +        return (NMSHandler.getVersion().isAtLeast(NMSVersion.v1_21) && entity.getBukkitEntity() instanceof Shearable
I think the parens are wrong here

2024-12-03 13:52 UTC, mcmonkey4eva commented on plugin/src/main/java/com/denizenscript/denizen/objects/properties/entity/EntitySheared.java
> +        if (getEntity() instanceof Shearable shearable) {
What happens with a sheep on a pre-1.21 server?

2024-12-03 15:50 UTC, mcmonkey4eva commented on paper/src/main/java/com/denizenscript/denizen/paper/properties/PaperEntityExtensions.java
> +import com.denizenscript.denizencore.utilities.debugging.Debug;
check your imports, these don't look to be actually used

2024-12-03 15:51 UTC, mcmonkey4eva commented on paper/src/main/java/com/denizenscript/denizen/paper/properties/PaperEntityExtensions.java
> +            // <--[mechanism]
put one blank line above the start of a meta block

2024-12-03 15:51 UTC, mcmonkey4eva commented on plugin/src/main/java/com/denizenscript/denizen/objects/properties/entity/EntitySheared.java
> +        } else if (getEntity() instanceof Snowman snowman) {
format

2024-12-03 15:52 UTC, mcmonkey4eva commented on plugin/src/main/java/com/denizenscript/denizen/objects/properties/entity/EntitySheared.java
> +        if (NMSHandler.getVersion().isAtLeast(NMSVersion.v1_21) && getEntity() instanceof Shearable shearable) {
version-specific checks should always be last in blocks like this

2024-12-05 00:30 UTC, mcmonkey4eva commented
To be clear: have you tested this PR on a pre-1.21 server?

2024-12-27 10:43 UTC, tal5 requested changes

2024-12-27 10:43 UTC, tal5 commented on paper/src/main/java/com/denizenscript/denizen/paper/properties/PaperEntityExtensions.java
> +                        if (input.matchesEnum(Sound.Source.class)) {
Should be able to use `Mechanism#requireEnum` here?
Also I'd probably replace the nested `if`s with early returns for better readability.

2024-12-27 10:43 UTC, tal5 commented on plugin/src/main/java/com/denizenscript/denizen/objects/properties/entity/EntitySheared.java
> +    public void setSheared(boolean sheared) {
Any reason to have these in separate methods? not necessarily a problem, but generally the logic is just directly in `get/setPropertyValue` (and e.g. the legacy `is_sheared` can just use `#getPropertyValue`)

2024-12-27 10:43 UTC, tal5 commented on plugin/src/main/java/com/denizenscript/denizen/utilities/BukkitImplDeprecations.java
> +    public static Warning entityIsSheared = new VerySlowWarning("entityIsSheared", "'EntityTag.is_sheared' property is deprecated in favor of 'EntityTag.sheared'.");
Pretty sure this would start out as a `FutureWarning`?

2024-12-27 10:43 UTC, tal5 commented on paper/src/main/java/com/denizenscript/denizen/paper/properties/PaperEntityExtensions.java
> +            // Valid types are AMBIENT, BLOCKS, HOSTILE, MASTER, MUSIC, NEUTRAL, PLAYERS, RECORDS, VOICE and WEATHER
The JD mentions entities that change entirely when sheared (e.g. mushroom cows becoming normal cows) becoming a different entity; probably a good idea to have a note for this here (and maybe link to https://meta.denizenscript.com/Docs/Events#entity%20transforms) as in some cases you'd have to get a new `EntityTag` if you want to do more stuff after shearing, or specifically have shearing be the last thing done.

2024-12-27 10:43 UTC, tal5 commented on paper/src/main/java/com/denizenscript/denizen/paper/properties/PaperEntityExtensions.java
> +            // Valid types are AMBIENT, BLOCKS, HOSTILE, MASTER, MUSIC, NEUTRAL, PLAYERS, RECORDS, VOICE and WEATHER
I'd link to the JD page for sound sources, saves us having to manually update it in the future.

2024-12-27 10:43 UTC, tal5 commented on plugin/src/main/java/com/denizenscript/denizen/objects/properties/entity/EntitySheared.java
> +    // To include drops or harvesting mushroom cows consider <@link mechanism EntityTag.shear>.
Nitpick, but
A. `bogged is harvested or a snow golem` missing `,`
B. `ie not wearing a pumpkin` probably in parenthesis?
C. `To include drops or harvesting mushroom cows consider` - `for harvesting`.

2024-12-27 15:54 UTC, mcmonkey4eva commented
also needs a merge fix due the deprecations file

2024-12-27 16:00 UTC, mcmonkey4eva commented on plugin/src/main/java/com/denizenscript/denizen/objects/properties/entity/EntitySheared.java
> +    // Controls whether a sheep is sheared, a bogged is harvested, or a snow golem is derped(ie not wearing a pumpkin).
space before the `(`

2024-12-27 16:01 UTC, mcmonkey4eva commented on plugin/src/main/java/com/denizenscript/denizen/objects/properties/entity/EntitySheared.java
> +        // Deprecated in favor of <@link mechanism EntityTag.sheared>.
need the `@deprecated` on this and above

2024-12-27 16:02 UTC, mcmonkey4eva commented on paper/src/main/java/com/denizenscript/denizen/paper/properties/PaperEntityExtensions.java
> +            // Shears a sheep, harvests a bogged or mushroom cow or derps a snow golem as a player would do, including drops.
This line is a bit of a mess. Maybe make it a list format?
```
This mech will:
- Shear a sheep
- harvest a bogged
- harvest a mushroom cow
- derp a snow golem
in the same way as a player can do using shears, including drops.
```

2024-12-27 16:03 UTC, mcmonkey4eva commented on paper/src/main/java/com/denizenscript/denizen/paper/properties/PaperEntityExtensions.java
> +            // Note: Mushroom cows will be replaced by entirely new 'cow' entities.
Implications? Does the UUID change, entity data is lost, ...?

2024-12-28 18:13 UTC, mcmonkey4eva commented on paper/src/main/java/com/denizenscript/denizen/paper/properties/PaperEntityExtensions.java
> +            // # - adjust <player.target> shear
syntax typo

2024-12-28 18:14 UTC, mcmonkey4eva commented on paper/src/main/java/com/denizenscript/denizen/paper/properties/PaperEntityExtensions.java
> +            // Valid sound sources can be found here: <@link url https://jd.advntr.dev/api/latest/net/kyori/adventure/sound/Sound.Source.html>.
link paper docs not that

2025-01-05 18:50 UTC, mcmonkey4eva approved these changes

2025-01-08 22:05 UTC, tal5 approved these changes

2025-01-08 22:06 UTC, merged

2025-01-25 02:20 UTC, mcmonkey4eva commented on paper/src/main/java/com/denizenscript/denizen/paper/properties/PaperEntityExtensions.java
> +            // @group paper
the `@input` value was missing here

2025-01-25 02:22 UTC, mcmonkey4eva commented on plugin/src/main/java/com/denizenscript/denizen/objects/properties/entity/EntitySheared.java
> +        // @deprecated use 'EntityTag.sheared'
this deprecated was put inside of the description which borked it