Determination format modernization Part.1
DenizenScript/Denizen-For-Bukkit pull request #2683
Opened 2024-12-10 10:39 UTC by MrMaleficus

Upgrading the `ApplyDetermination` format to the new standard on the following events : 

- `BlockCooksSmeltsItemScriptEvent`
- `PlayerClicksInInventoryScriptEvent`

2024-12-10 11:02 UTC, tal5 requested changes

2024-12-10 11:02 UTC, tal5 commented on plugin/src/main/java/com/denizenscript/denizen/events/block/BlockCooksSmeltsItemScriptEvent.java
> +            case "source_item" -> new ItemTag(event.getSource());
Correct me if I'm wrong, but I don't think the source item can change (I.e. can just use the field for it)?

2024-12-10 11:02 UTC, tal5 commented on plugin/src/main/java/com/denizenscript/denizen/events/player/PlayerClicksInInventoryScriptEvent.java
> +    // HOTBAR_MOVE_AND_READ
This isn't a typo, it's saying "re-add"; see https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/inventory/InventoryAction.html
![image](https://github.com/user-attachments/assets/f5648368-3c64-4649-90e1-048c1a62a301)

2024-12-10 11:02 UTC, tal5 commented on plugin/src/main/java/com/denizenscript/denizen/events/player/PlayerClicksInInventoryScriptEvent.java
> +                } else {
`else` on a new line - alternatively could also use a ternary expression here, but either way is fine.

2024-12-10 11:06 UTC, MrMaleficus commented on plugin/src/main/java/com/denizenscript/denizen/events/block/BlockCooksSmeltsItemScriptEvent.java
> +            case "source_item" -> new ItemTag(event.getSource());
Indeed, fixing

2024-12-10 11:09 UTC, MrMaleficus commented
Updated

2024-12-10 20:23 UTC, mcmonkey4eva approved these changes

2024-12-25 15:05 UTC, tal5 approved these changes

2024-12-25 15:08 UTC, merged